### ISSUE TITLE
broken on new version of go playground

### ISSUE THREAD

**Issue by audiolion** [dancannon/better-go-playground#5]
![image](https://user-images.githubusercontent.com/2430381/81428369-2c883780-912a-11ea-80a6-2a8179da29b7.png)

The element with id "controls" no longer exists:

![image](https://user-images.githubusercontent.com/2430381/81428426-3d38ad80-912a-11ea-93d2-697ab3e6d991.png)

**Comment by dancannon** [comment]
Thanks for reporting, I'll try and get this fixed ASAP.

**Comment by dancannon** [comment]
That took significantly longer than I expected but I have just pushed a new version of the extension to the Chrome store which should hopefully fix this bug. I have also taken the opportunity to refactor the JS and to integrate more cleanly with the Playground code, hopefully it should be less likely to break in the future.

I am not sure when the extension will be approved by Google but if you could check back later and let me know if the issue is fixed for you that would be greatly appreciated. Thanks again!

**Comment by audiolion** [comment]
Working great, thank you so much!
